version: '3.8'
services:
  app:
    build: ./app
    environment:
      MYSQL_HOST: localhost  
    ports:
      - "5000:5000"
      
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

